/* Auto-generated by scripts/generate-properties.mjs — do not edit manually */
export type Apartment = {
  id: string;
  folderName: string;
  number: number;
  label: string;
  labelKey: string;
  imageCount: number;
  coverImage: string;
  images: string[];
};

export type Property = {
  id: string;
  address: string;
  apartmentCount: number;
  coverImage: string;
  apartments: Apartment[];
};

export const properties: Property[] = [
  {
    "id": "hanoter-26",
    "address": "HaNoter 26",
    "apartmentCount": 3,
    "coverImage": "/HaNoter%2026/1/%D7%9E%D7%98%D7%91%D7%97%20%D7%95%D7%A1%D7%9C%D7%95%D7%9F.jpg",
    "apartments": [
      {
        "id": "hanoter-26-1",
        "folderName": "1",
        "number": 1,
        "label": "",
        "labelKey": "",
        "imageCount": 4,
        "coverImage": "/HaNoter%2026/1/%D7%9E%D7%98%D7%91%D7%97%20%D7%95%D7%A1%D7%9C%D7%95%D7%9F.jpg",
        "images": [
          "/HaNoter%2026/1/%D7%97%D7%93%D7%A8%20%D7%A9%D7%99%D7%A0%D7%94.jpg",
          "/HaNoter%2026/1/%D7%9E%D7%98%D7%91%D7%97%20%D7%95%D7%A1%D7%9C%D7%95%D7%9F.jpg",
          "/HaNoter%2026/1/%D7%9E%D7%A7%D7%9C%D7%97%D7%AA.jpg",
          "/HaNoter%2026/1/%D7%A1%D7%9C%D7%95%D7%9F.jpg"
        ]
      },
      {
        "id": "hanoter-26-2",
        "folderName": "2",
        "number": 2,
        "label": "",
        "labelKey": "",
        "imageCount": 6,
        "coverImage": "/HaNoter%2026/2/%D7%A1%D7%9C%D7%95%D7%9F%20%D7%95%D7%9E%D7%98%D7%91%D7%97.jpg",
        "images": [
          "/HaNoter%2026/2/%D7%97%D7%93%D7%A8%20%D7%A9%D7%99%D7%A0%D7%94.jpg",
          "/HaNoter%2026/2/%D7%9E%D7%98%D7%91%D7%97.jpg",
          "/HaNoter%2026/2/%D7%A1%D7%9C%D7%95%D7%9F%20%D7%95%D7%9E%D7%98%D7%91%D7%97.jpg",
          "/HaNoter%2026/2/%D7%A1%D7%9C%D7%95%D7%9F.jpg",
          "/HaNoter%2026/2/%D7%A1%D7%A4%D7%94.jpg",
          "/HaNoter%2026/2/%D7%A9%D7%99%D7%A8%D7%95%D7%AA%D7%99%D7%9D.jpg"
        ]
      },
      {
        "id": "hanoter-26-3",
        "folderName": "3",
        "number": 3,
        "label": "",
        "labelKey": "",
        "imageCount": 4,
        "coverImage": "/HaNoter%2026/3/%D7%A1%D7%9C%D7%95%D7%9F%20%D7%95%D7%9E%D7%98%D7%91%D7%97.jpg",
        "images": [
          "/HaNoter%2026/3/%D7%97%D7%93%D7%A8%20%D7%A9%D7%99%D7%A0%D7%94.jpg",
          "/HaNoter%2026/3/%D7%9E%D7%A7%D7%9C%D7%97%D7%AA.jpg",
          "/HaNoter%2026/3/%D7%A1%D7%9C%D7%95%D7%9F%20%D7%95%D7%9E%D7%98%D7%91%D7%97.jpg",
          "/HaNoter%2026/3/%D7%A1%D7%9C%D7%95%D7%9F.jpg"
        ]
      }
    ]
  },
  {
    "id": "negba-21",
    "address": "Negba 21",
    "apartmentCount": 2,
    "coverImage": "/Negba%2021/1/%D7%A1%D7%9C%D7%95%D7%9F%202.jpeg",
    "apartments": [
      {
        "id": "negba-21-1",
        "folderName": "1",
        "number": 1,
        "label": "",
        "labelKey": "",
        "imageCount": 11,
        "coverImage": "/Negba%2021/1/%D7%A1%D7%9C%D7%95%D7%9F%202.jpeg",
        "images": [
          "/Negba%2021/1/%D7%97%D7%93%D7%A8%20%D7%A9%D7%99%D7%A0%D7%94%202.jpeg",
          "/Negba%2021/1/%D7%97%D7%93%D7%A8%20%D7%A9%D7%99%D7%A0%D7%94.jpeg",
          "/Negba%2021/1/%D7%9E%D7%98%D7%91%D7%97%202.jpeg",
          "/Negba%2021/1/%D7%9E%D7%98%D7%91%D7%97%203.jpeg",
          "/Negba%2021/1/%D7%9E%D7%98%D7%91%D7%97.jpeg",
          "/Negba%2021/1/%D7%A1%D7%9C%D7%95%D7%9F%202.jpeg",
          "/Negba%2021/1/%D7%A1%D7%9C%D7%95%D7%9F%203.jpeg",
          "/Negba%2021/1/%D7%A1%D7%9C%D7%95%D7%9F%20%D7%95%D7%97%D7%A6%D7%A8.jpeg",
          "/Negba%2021/1/%D7%A4%D7%99%D7%A0%D7%AA%20%D7%90%D7%95%D7%9B%D7%9C.jpeg",
          "/Negba%2021/1/%D7%A9%D7%99%D7%A8%D7%95%D7%AA%D7%99%D7%9D%20%D7%95%D7%9E%D7%A7%D7%9C%D7%97%D7%AA.jpeg",
          "/Negba%2021/1/%D7%A9%D7%99%D7%A8%D7%95%D7%AA%D7%99%D7%9D.jpeg"
        ]
      },
      {
        "id": "negba-21-2",
        "folderName": "2",
        "number": 2,
        "label": "",
        "labelKey": "",
        "imageCount": 12,
        "coverImage": "/Negba%2021/2/%D7%A1%D7%9C%D7%95%D7%9F%202.jpeg",
        "images": [
          "/Negba%2021/2/%D7%92%D7%99%D7%A0%D7%94%202.jpeg",
          "/Negba%2021/2/%D7%92%D7%99%D7%A0%D7%94.jpeg",
          "/Negba%2021/2/%D7%93%D7%9C%D7%AA%20%D7%9B%D7%A0%D7%99%D7%A1%D7%94.jpeg",
          "/Negba%2021/2/%D7%97%D7%93%D7%A8%20%D7%A9%D7%99%D7%A0%D7%94%202.jpeg",
          "/Negba%2021/2/%D7%97%D7%93%D7%A8%20%D7%A9%D7%99%D7%A0%D7%94%20%D7%95%D7%97%D7%A6%D7%A8.jpeg",
          "/Negba%2021/2/%D7%97%D7%93%D7%A8%20%D7%A9%D7%99%D7%A0%D7%94.jpeg",
          "/Negba%2021/2/%D7%9E%D7%98%D7%91%D7%97.jpeg",
          "/Negba%2021/2/%D7%A1%D7%9C%D7%95%D7%9F%202.jpeg",
          "/Negba%2021/2/%D7%A1%D7%9C%D7%95%D7%9F%203.jpeg",
          "/Negba%2021/2/%D7%A1%D7%9C%D7%95%D7%9F.jpeg",
          "/Negba%2021/2/%D7%A9%D7%99%D7%A8%D7%95%D7%AA%D7%99%D7%9D%20%D7%95%D7%9E%D7%A7%D7%9C%D7%97%D7%AA.jpeg",
          "/Negba%2021/2/%D7%A9%D7%99%D7%A8%D7%95%D7%AA%D7%99%D7%9D.jpeg"
        ]
      }
    ]
  },
  {
    "id": "ramkhal-4",
    "address": "Ramkhal 4",
    "apartmentCount": 4,
    "coverImage": "/Ramkhal%204/1%20balcony/%D7%A1%D7%9C%D7%95%D7%9F.jpg",
    "apartments": [
      {
        "id": "ramkhal-4-1",
        "folderName": "1 balcony",
        "number": 1,
        "label": "balcony",
        "labelKey": "balcony",
        "imageCount": 7,
        "coverImage": "/Ramkhal%204/1%20balcony/%D7%A1%D7%9C%D7%95%D7%9F.jpg",
        "images": [
          "/Ramkhal%204/1%20balcony/%D7%97%D7%93%D7%A8%20%D7%A9%D7%99%D7%A0%D7%94.jpg",
          "/Ramkhal%204/1%20balcony/%D7%9E%D7%98%D7%91%D7%97.jpg",
          "/Ramkhal%204/1%20balcony/%D7%9E%D7%A7%D7%9C%D7%97%D7%AA.jpg",
          "/Ramkhal%204/1%20balcony/%D7%9E%D7%A8%D7%A4%D7%A1%D7%AA%202.jpg",
          "/Ramkhal%204/1%20balcony/%D7%9E%D7%A8%D7%A4%D7%A1%D7%AA.jpg",
          "/Ramkhal%204/1%20balcony/%D7%A1%D7%9C%D7%95%D7%9F.jpg",
          "/Ramkhal%204/1%20balcony/%D7%A9%D7%99%D7%A8%D7%95%D7%AA%D7%99%D7%9D.jpg"
        ]
      },
      {
        "id": "ramkhal-4-2",
        "folderName": "2 bombshelter",
        "number": 2,
        "label": "bombshelter",
        "labelKey": "bombshelter",
        "imageCount": 7,
        "coverImage": "/Ramkhal%204/2%20bombshelter/%D7%A1%D7%9C%D7%95%D7%9F%202.jpg",
        "images": [
          "/Ramkhal%204/2%20bombshelter/%D7%97%D7%93%D7%A8%20%D7%A9%D7%99%D7%A0%D7%94%20%D7%95%D7%9E%D7%9E%D7%93.jpg",
          "/Ramkhal%204/2%20bombshelter/%D7%9E%D7%98%D7%91%D7%97.jpg",
          "/Ramkhal%204/2%20bombshelter/%D7%A1%D7%9C%D7%95%D7%9F%202.jpg",
          "/Ramkhal%204/2%20bombshelter/%D7%A1%D7%9C%D7%95%D7%9F%20%D7%95%D7%9E%D7%98%D7%91%D7%97%202.jpg",
          "/Ramkhal%204/2%20bombshelter/%D7%A1%D7%9C%D7%95%D7%9F%20%D7%95%D7%9E%D7%98%D7%91%D7%97.jpg",
          "/Ramkhal%204/2%20bombshelter/%D7%A1%D7%9C%D7%95%D7%9F.jpg",
          "/Ramkhal%204/2%20bombshelter/%D7%A9%D7%99%D7%A8%D7%95%D7%AA%D7%99%D7%9D.jpg"
        ]
      },
      {
        "id": "ramkhal-4-3",
        "folderName": "3 garden",
        "number": 3,
        "label": "garden",
        "labelKey": "garden",
        "imageCount": 9,
        "coverImage": "/Ramkhal%204/3%20garden/%D7%A1%D7%9C%D7%95%D7%9F%202.jpg",
        "images": [
          "/Ramkhal%204/3%20garden/%D7%97%D7%93%D7%A8%20%D7%A9%D7%99%D7%A0%D7%94%202.jpg",
          "/Ramkhal%204/3%20garden/%D7%97%D7%93%D7%A8%20%D7%A9%D7%99%D7%A0%D7%94.jpg",
          "/Ramkhal%204/3%20garden/%D7%97%D7%A6%D7%A8%202.jpg",
          "/Ramkhal%204/3%20garden/%D7%97%D7%A6%D7%A8.jpg",
          "/Ramkhal%204/3%20garden/%D7%9E%D7%98%D7%91%D7%97.jpg",
          "/Ramkhal%204/3%20garden/%D7%A1%D7%9C%D7%95%D7%9F%202.jpg",
          "/Ramkhal%204/3%20garden/%D7%A1%D7%9C%D7%95%D7%9F%20%D7%95%D7%9E%D7%98%D7%91%D7%97.jpg",
          "/Ramkhal%204/3%20garden/%D7%A1%D7%9C%D7%95%D7%9F.jpg",
          "/Ramkhal%204/3%20garden/%D7%A9%D7%99%D7%A8%D7%95%D7%AA%D7%99%D7%9D.jpg"
        ]
      },
      {
        "id": "ramkhal-4-4",
        "folderName": "4",
        "number": 4,
        "label": "",
        "labelKey": "",
        "imageCount": 8,
        "coverImage": "/Ramkhal%204/4/%D7%A1%D7%9C%D7%95%D7%9F%20%D7%95%D7%9E%D7%98%D7%91%D7%97.jpg",
        "images": [
          "/Ramkhal%204/4/%D7%97%D7%93%D7%A8%20%D7%A9%D7%99%D7%A0%D7%94%202.jpg",
          "/Ramkhal%204/4/%D7%97%D7%93%D7%A8%20%D7%A9%D7%99%D7%A0%D7%94.jpg",
          "/Ramkhal%204/4/%D7%9B%D7%A0%D7%99%D7%A1%D7%94.jpg",
          "/Ramkhal%204/4/%D7%9E%D7%98%D7%91%D7%97%202.jpg",
          "/Ramkhal%204/4/%D7%9E%D7%98%D7%91%D7%97.jpg",
          "/Ramkhal%204/4/%D7%A1%D7%9C%D7%95%D7%9F%20%D7%95%D7%9E%D7%98%D7%91%D7%97.jpg",
          "/Ramkhal%204/4/%D7%A1%D7%9C%D7%95%D7%9F.jpg",
          "/Ramkhal%204/4/%D7%A9%D7%99%D7%A8%D7%95%D7%AA%D7%99%D7%9D.jpg"
        ]
      }
    ]
  },
  {
    "id": "wingate-70",
    "address": "Wingate 70",
    "apartmentCount": 2,
    "coverImage": "/Wingate%2070/1/%D7%A1%D7%9C%D7%95%D7%9F%20%D7%95%D7%9E%D7%98%D7%91%D7%97.png",
    "apartments": [
      {
        "id": "wingate-70-1",
        "folderName": "1",
        "number": 1,
        "label": "",
        "labelKey": "",
        "imageCount": 5,
        "coverImage": "/Wingate%2070/1/%D7%A1%D7%9C%D7%95%D7%9F%20%D7%95%D7%9E%D7%98%D7%91%D7%97.png",
        "images": [
          "/Wingate%2070/1/%D7%97%D7%93%D7%A8%20%D7%A9%D7%99%D7%A0%D7%94.png",
          "/Wingate%2070/1/%D7%9E%D7%99%D7%98%D7%94.jpg",
          "/Wingate%2070/1/%D7%A1%D7%9C%D7%95%D7%9F%20%D7%95%D7%9E%D7%98%D7%91%D7%97.png",
          "/Wingate%2070/1/%D7%A1%D7%9C%D7%95%D7%9F.jpg",
          "/Wingate%2070/1/%D7%A9%D7%99%D7%A8%D7%95%D7%AA%D7%99%D7%9D.jpg"
        ]
      },
      {
        "id": "wingate-70-2",
        "folderName": "2",
        "number": 2,
        "label": "",
        "labelKey": "",
        "imageCount": 6,
        "coverImage": "/Wingate%2070/2/%D7%A1%D7%9C%D7%95%D7%9F%20%D7%95%D7%9E%D7%98%D7%91%D7%97.jpg",
        "images": [
          "/Wingate%2070/2/%D7%97%D7%93%D7%A8%20%D7%A9%D7%99%D7%A0%D7%94.jpg",
          "/Wingate%2070/2/%D7%9E%D7%98%D7%91%D7%97.jpg",
          "/Wingate%2070/2/%D7%A1%D7%9C%D7%95%D7%9F%20%D7%95%D7%9E%D7%98%D7%91%D7%97.jpg",
          "/Wingate%2070/2/%D7%A1%D7%9C%D7%95%D7%9F.jpg",
          "/Wingate%2070/2/%D7%A9%D7%95%D7%9C%D7%97%D7%9F%20%D7%A1%D7%9C%D7%95%D7%9F.jpg",
          "/Wingate%2070/2/%D7%A9%D7%99%D7%A8%D7%95%D7%AA%D7%99%D7%9D.jpg"
        ]
      }
    ]
  }
];

export const propertyCountBySize = properties.reduce<Record<number, number>>(
  (counts, property) => {
    counts[property.apartmentCount] =
      (counts[property.apartmentCount] ?? 0) + 1;
    return counts;
  },
  {},
);
